
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 25 01:12:29 VET 2013
//----------------------------------------------------

package thinice.parser;

/** CUP generated interface containing symbol constants. */
public interface ThinIceTokenDef {
  /* terminals */
  public static final int LLA_I = 5;
  public static final int ENTERO = 34;
  public static final int LLA_D = 6;
  public static final int DIFERENTE = 32;
  public static final int RESTA = 20;
  public static final int INT = 11;
  public static final int FOR = 17;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int IGUAL = 31;
  public static final int OR = 25;
  public static final int DIV = 22;
  public static final int SUMA = 19;
  public static final int IF = 13;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 12;
  public static final int ASIG = 18;
  public static final int PAR_I = 3;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 10;
  public static final int PAR_D = 4;
  public static final int MENOR = 27;
  public static final int MOD = 23;
  public static final int PUNT_C = 9;
  public static final int ERROR = 36;
  public static final int MAYOR = 29;
  public static final int ELSE = 14;
  public static final int WHILE = 16;
  public static final int MAYOR_IGUAL = 30;
  public static final int COR_I = 7;
  public static final int MULTI = 21;
  public static final int BOOLEANO = 33;
  public static final int COR_D = 8;
  public static final int MENOR_IGUAL = 28;
  public static final int DO = 15;
}

