
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 21 02:09:28 VET 2013
//----------------------------------------------------

package thinice.parser;

/** CUP generated interface containing symbol constants. */
public interface ThinIceTokenDef {
  /* terminals */
  public static final int LLA_I = 5;
  public static final int EMPTY = 35;
  public static final int ENTERO = 33;
  public static final int LLA_D = 6;
  public static final int DIFERENTE = 31;
  public static final int RESTA = 19;
  public static final int INT = 10;
  public static final int FOR = 16;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int IGUAL = 30;
  public static final int OR = 24;
  public static final int BOOL = 11;
  public static final int DIV = 21;
  public static final int SUMA = 18;
  public static final int IF = 12;
  public static final int ID = 34;
  public static final int EOF = 0;
  public static final int ASIG = 17;
  public static final int PAR_I = 3;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PAR_D = 4;
  public static final int MENOR = 26;
  public static final int MOD = 22;
  public static final int PUNT_C = 9;
  public static final int ERROR = 36;
  public static final int MAYOR = 28;
  public static final int ELSE = 13;
  public static final int WHILE = 15;
  public static final int MAYOR_IGUAL = 29;
  public static final int COR_I = 7;
  public static final int MULTI = 20;
  public static final int BOOLEANO = 32;
  public static final int COR_D = 8;
  public static final int MENOR_IGUAL = 27;
  public static final int DO = 14;
}

