
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 19 18:47:05 VET 2013
//----------------------------------------------------

package thinice.especificaciones;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PROGRAMA = 2;
  public static final int MENOR = 13;
  public static final int OP_MULTI = 6;
  public static final int TIPOENTERO = 31;
  public static final int IGUAL = 17;
  public static final int OP_NEG = 12;
  public static final int LLA_IZ = 21;
  public static final int PAR_DE = 20;
  public static final int HASTA = 28;
  public static final int MENOR_IGUAL = 14;
  public static final int MAYOR_IGUAL = 16;
  public static final int ID = 34;
  public static final int PARA = 29;
  public static final int OP_DISJ = 11;
  public static final int OP_SUMA = 4;
  public static final int OP_DIVI = 7;
  public static final int TIPOBOOL = 30;
  public static final int PAR_IZ = 19;
  public static final int MAYOR = 15;
  public static final int EOF = 0;
  public static final int DIFERENTE = 18;
  public static final int SINO = 26;
  public static final int SI = 25;
  public static final int OP_MODU = 8;
  public static final int error = 1;
  public static final int COR_DE = 24;
  public static final int BOOL = 32;
  public static final int ASIGNA = 9;
  public static final int ENTERO = 33;
  public static final int OP_CONJ = 10;
  public static final int OP_RESTA = 5;
  public static final int PCOMA = 3;
  public static final int LLA_DE = 22;
  public static final int REPITA = 27;
  public static final int COR_IZ = 23;
}

