/* The following code was generated by JFlex 1.4.3 on 26/10/13 07:05 PM */

package thinice.lexer;

import java_cup.runtime.*;
import thinice.parser.ThinIceTokenDef;
import thinice.TS.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 26/10/13 07:05 PM from the specification file
 * <tt>src/thinice/lexer/ThinIceInterpreter.flex</tt>
 */
public class ThinIceLexer implements java_cup.runtime.Scanner, ThinIceTokenDef {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 13, 12,  0, 13, 11,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    13, 41,  0,  0,  0,  0,  0,  0, 29, 30, 14, 37, 22, 38, 16, 15, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 35, 21, 42, 36, 43,  0, 
     0,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 40, 
     2,  2,  2,  2,  2,  2,  2,  2,  2, 39,  2, 33,  0, 34,  0, 16, 
     0,  8, 23,  2, 26,  6,  7, 19, 28, 25,  2,  2,  9, 20, 24, 18, 
    17,  2,  4, 10,  3,  5,  2, 27,  2,  2,  2, 31,  0, 32,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\4\3\2\4\1\5\1\6\1\1"+
    "\1\3\1\7\1\10\4\3\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\1\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\3\1\1\5\3\3\0\2\3"+
    "\1\27\1\30\1\3\1\31\1\32\1\33\1\34\5\3"+
    "\1\35\2\0\1\36\3\3\1\37\1\40\1\3\1\0"+
    "\1\4\5\3\1\41\1\3\1\42\4\3\1\43\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\130\0\130\0\u018c\0\u01b8\0\u01e4\0\130\0\130"+
    "\0\u0210\0\u023c\0\u0268\0\u0294\0\130\0\130\0\130\0\130"+
    "\0\130\0\130\0\u02c0\0\130\0\130\0\130\0\260\0\260"+
    "\0\130\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4"+
    "\0\u0420\0\u044c\0\u0478\0\u04a4\0\u01b8\0\u04d0\0\u04fc\0\260"+
    "\0\260\0\u0528\0\130\0\130\0\130\0\130\0\u0554\0\u0580"+
    "\0\u05ac\0\u05d8\0\u0604\0\260\0\u0630\0\u065c\0\260\0\u0688"+
    "\0\u06b4\0\u06e0\0\260\0\260\0\u070c\0\u0738\0\u0630\0\u0764"+
    "\0\u0790\0\u07bc\0\u07e8\0\u0814\0\260\0\u0840\0\260\0\u086c"+
    "\0\u0898\0\u08c4\0\u08f0\0\260\0\260";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\5\1\7\1\10\3\5"+
    "\1\11\2\12\1\13\1\14\1\15\3\5\1\16\1\17"+
    "\1\20\1\21\1\5\1\22\1\23\1\24\1\5\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\3\1\4"+
    "\1\5\1\6\2\5\1\7\1\10\3\5\1\11\2\12"+
    "\1\13\1\14\1\15\1\44\2\5\1\16\1\17\1\20"+
    "\1\21\1\5\1\22\1\23\1\24\1\5\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\55\0\1\4\11\45"+
    "\5\0\5\45\2\0\6\45\12\0\2\45\4\0\1\45"+
    "\11\5\5\0\1\45\4\5\2\0\6\5\12\0\2\5"+
    "\4\0\1\45\2\5\1\46\6\5\5\0\1\45\4\5"+
    "\2\0\6\5\12\0\2\5\4\0\1\45\7\5\1\47"+
    "\1\5\5\0\1\45\4\5\2\0\1\5\1\50\4\5"+
    "\12\0\2\5\4\0\1\45\6\5\1\51\2\5\5\0"+
    "\1\45\1\5\1\52\2\5\2\0\6\5\12\0\2\5"+
    "\17\0\1\12\55\0\1\53\1\54\35\0\12\45\5\0"+
    "\1\55\4\45\2\0\6\45\12\0\2\45\4\0\1\45"+
    "\11\5\5\0\1\45\1\5\1\56\2\5\2\0\6\5"+
    "\12\0\2\5\4\0\1\45\11\5\5\0\1\45\1\5"+
    "\1\57\2\5\2\0\6\5\12\0\2\5\4\0\1\45"+
    "\5\5\1\60\3\5\5\0\1\45\4\5\2\0\6\5"+
    "\12\0\2\5\4\0\1\45\11\5\5\0\1\45\1\5"+
    "\1\61\2\5\2\0\6\5\12\0\2\5\4\0\1\45"+
    "\11\5\5\0\1\45\4\5\2\0\5\5\1\62\12\0"+
    "\2\5\47\0\1\63\53\0\1\64\6\0\1\65\44\0"+
    "\1\66\10\0\1\45\2\5\1\67\6\5\5\0\1\45"+
    "\4\5\2\0\6\5\12\0\2\5\4\0\12\45\5\0"+
    "\5\45\2\0\6\45\12\0\2\45\4\0\1\45\3\5"+
    "\1\70\5\5\5\0\1\45\4\5\2\0\6\5\12\0"+
    "\2\5\4\0\1\45\10\5\1\71\5\0\1\45\4\5"+
    "\2\0\6\5\12\0\2\5\4\0\1\45\1\5\1\72"+
    "\7\5\5\0\1\45\4\5\2\0\6\5\12\0\2\5"+
    "\4\0\1\45\7\5\1\73\1\5\5\0\1\45\4\5"+
    "\2\0\6\5\12\0\2\5\4\0\1\45\2\5\1\74"+
    "\6\5\5\0\1\45\4\5\2\0\6\5\12\0\2\5"+
    "\3\0\16\75\1\76\35\75\13\54\1\11\1\12\37\54"+
    "\1\0\1\45\11\5\5\0\1\45\4\5\2\0\3\5"+
    "\1\77\2\5\12\0\2\5\4\0\1\45\11\5\5\0"+
    "\1\45\1\5\1\100\2\5\2\0\6\5\12\0\2\5"+
    "\4\0\1\45\11\5\5\0\1\45\4\5\2\0\2\5"+
    "\1\101\3\5\12\0\2\5\4\0\1\45\11\5\5\0"+
    "\1\45\1\5\1\102\2\5\2\0\6\5\12\0\2\5"+
    "\4\0\1\45\4\5\1\103\4\5\5\0\1\45\4\5"+
    "\2\0\6\5\12\0\2\5\4\0\1\45\4\5\1\104"+
    "\4\5\5\0\1\45\4\5\2\0\6\5\12\0\2\5"+
    "\4\0\1\45\4\5\1\105\4\5\5\0\1\45\4\5"+
    "\2\0\6\5\12\0\2\5\4\0\1\45\10\5\1\70"+
    "\5\0\1\45\4\5\2\0\6\5\12\0\2\5\3\0"+
    "\16\75\1\106\53\75\1\106\1\107\34\75\1\0\1\45"+
    "\7\5\1\110\1\5\5\0\1\45\4\5\2\0\6\5"+
    "\12\0\2\5\4\0\1\45\7\5\1\111\1\5\5\0"+
    "\1\45\4\5\2\0\6\5\12\0\2\5\4\0\1\45"+
    "\11\5\5\0\1\45\2\5\1\112\1\5\2\0\6\5"+
    "\12\0\2\5\4\0\1\45\2\5\1\113\6\5\5\0"+
    "\1\45\4\5\2\0\6\5\12\0\2\5\3\0\16\75"+
    "\1\106\1\12\34\75\1\0\1\45\4\5\1\114\4\5"+
    "\5\0\1\45\4\5\2\0\6\5\12\0\2\5\4\0"+
    "\1\45\4\5\1\115\4\5\5\0\1\45\4\5\2\0"+
    "\6\5\12\0\2\5\4\0\1\45\2\5\1\116\6\5"+
    "\5\0\1\45\4\5\2\0\6\5\12\0\2\5\4\0"+
    "\1\45\11\5\5\0\1\45\1\5\1\117\2\5\2\0"+
    "\6\5\12\0\2\5\4\0\1\45\6\5\1\120\2\5"+
    "\5\0\1\45\4\5\2\0\6\5\12\0\2\5\4\0"+
    "\1\45\6\5\1\121\2\5\5\0\1\45\4\5\2\0"+
    "\6\5\12\0\2\5\4\0\1\45\11\5\5\0\1\45"+
    "\4\5\2\0\1\5\1\122\4\5\12\0\2\5\4\0"+
    "\1\45\11\5\5\0\1\45\3\5\1\123\2\0\6\5"+
    "\12\0\2\5\4\0\1\45\11\5\5\0\1\45\1\5"+
    "\1\124\2\5\2\0\6\5\12\0\2\5\4\0\1\45"+
    "\6\5\1\125\2\5\5\0\1\45\4\5\2\0\6\5"+
    "\12\0\2\5\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2332];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\2\11\3\1\2\11\4\1\6\11"+
    "\1\1\3\11\2\1\1\11\11\1\3\0\5\1\4\11"+
    "\6\1\2\0\7\1\1\0\17\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private SimboloAbstracto nombreArchivo;
	
	public int getLinea(){
		return yyline+1;
	}
	
	public int getColumna(){
		return yycolumn+1;
	}

	private Symbol symbol(int type) {
		return new Symbol(type, yyline + 1, yycolumn + 1);
	}

	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline + 1, yycolumn + 1, value);
	}

	public void setNombreArchivo(String nombre) {
		nombreArchivo = TablaAbstracta.texTabla.agregarSimbolo(nombre, getLinea(), getColumna());
	}

	public SimboloAbstracto getNombreArchivo() {
		return nombreArchivo;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ThinIceLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ThinIceLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return symbol(BOOLEANO,		TablaAbstracta.boolTabla.agregarSimbolo(yytext(), getLinea(), getColumna()));
          }
        case 37: break;
        case 23: 
          { return symbol(IF,				new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 38: break;
        case 28: 
          { return symbol(MAYOR_IGUAL,	new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 39: break;
        case 15: 
          { return symbol(IGUAL,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 40: break;
        case 16: 
          { return symbol(SUMA,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 41: break;
        case 18: 
          { return symbol(AND,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 42: break;
        case 7: 
          { return symbol(PUNT_C,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 43: break;
        case 1: 
          { return symbol(ERROR,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 44: break;
        case 21: 
          { return symbol(MENOR,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 45: break;
        case 36: 
          { return symbol(PROGRAM,		new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 46: break;
        case 22: 
          { return symbol(MAYOR,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 47: break;
        case 30: 
          { return symbol(MOD,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 48: break;
        case 11: 
          { return symbol(LLA_I,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 49: break;
        case 9: 
          { return symbol(PAR_I,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 50: break;
        case 17: 
          { return symbol(RESTA,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 51: break;
        case 35: 
          { return symbol(BOOLEAN,		new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 52: break;
        case 19: 
          { return symbol(OR,				new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 53: break;
        case 3: 
          { return symbol(ID,				TablaAbstracta.idTabla.agregarSimbolo(yytext(), getLinea(), getColumna()));
          }
        case 54: break;
        case 13: 
          { return symbol(COR_I,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 55: break;
        case 5: 
          { return symbol(MULTI,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 56: break;
        case 33: 
          { return symbol(WHILE,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 57: break;
        case 12: 
          { return symbol(LLA_D,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 58: break;
        case 6: 
          { return symbol(DIV,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 59: break;
        case 24: 
          { return symbol(DO,				new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 60: break;
        case 10: 
          { return symbol(PAR_D,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 61: break;
        case 26: 
          { return symbol(MENOR_IGUAL,	new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 62: break;
        case 25: 
          { return symbol(ASIG,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 63: break;
        case 34: 
          { return symbol(INT,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 64: break;
        case 32: 
          { return symbol(ELSE,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 65: break;
        case 29: 
          { return symbol(FOR,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 66: break;
        case 20: 
          { return symbol(NOT,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 67: break;
        case 27: 
          { return symbol(DIFERENTE,		new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 68: break;
        case 8: 
          { return symbol(COMA,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 69: break;
        case 14: 
          { return symbol(COR_D,			new SimboloTexto(yytext(), getLinea(), getColumna()));
          }
        case 70: break;
        case 2: 
          { return symbol(ENTERO,			TablaAbstracta.intTabla.agregarSimbolo(yytext(), getLinea(), getColumna()));
          }
        case 71: break;
        case 4: 
          { 
          }
        case 72: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	return symbol(EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
