/* The following code was generated by JFlex 1.4.3 on 21/10/13 02:09 AM */

package thinice.lexer;

import java_cup.runtime.*;
import JFlex.sym;
import thinice.parser.ThinIceTokenDef;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 21/10/13 02:09 AM from the specification file
 * <tt>src/thinice/lexer/ThinIceInterpreter.flex</tt>
 */
public class ThinIceLexer implements ThinIceTokenDef, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1, 32,  0,  0,  0,  0,  0,  0, 20, 21,  3, 27,  0, 28,  0,  2, 
    37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 25, 11, 33, 26, 34,  0, 
     0, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 31, 
    38, 38, 38, 38, 38, 38, 38, 38, 38, 30, 38, 23,  0, 24,  0,  0, 
     0,  9, 12, 38, 29, 14, 36,  8, 19, 18, 38, 38, 13, 10, 15,  7, 
     5, 38,  6, 17, 16, 35, 38, 38, 38, 38, 38, 22,  0,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\4\6\1\7"+
    "\5\6\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\6"+
    "\1\25\1\6\1\0\6\6\1\26\1\6\1\27\1\30"+
    "\1\31\1\32\2\6\1\0\2\6\1\33\7\6\1\2"+
    "\1\34\3\6\1\35\1\36\5\6\1\37\1\6\1\40"+
    "\1\6\1\41\3\6\1\42\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\116\0\165\0\116\0\116\0\234"+
    "\0\303\0\352\0\u0111\0\116\0\u0138\0\u015f\0\u0186\0\u01ad"+
    "\0\u01d4\0\116\0\116\0\116\0\116\0\116\0\u01fb\0\116"+
    "\0\116\0\116\0\352\0\352\0\116\0\u0222\0\u0249\0\u0270"+
    "\0\u0297\0\u02be\0\u02e5\0\u030c\0\u0333\0\u035a\0\u0381\0\u03a8"+
    "\0\u03cf\0\u03f6\0\u041d\0\116\0\116\0\116\0\116\0\u0444"+
    "\0\u046b\0\u0492\0\u04b9\0\u04e0\0\352\0\u0507\0\u052e\0\u0555"+
    "\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u02e5\0\352\0\u0618\0\u063f"+
    "\0\u0666\0\352\0\352\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729"+
    "\0\352\0\u0750\0\352\0\u0777\0\352\0\u079e\0\u07c5\0\u07ec"+
    "\0\352\0\352";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\3\12"+
    "\1\13\1\14\1\15\1\12\1\16\1\12\1\17\1\20"+
    "\1\12\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\12\1\33\1\34\1\35\1\36"+
    "\1\37\1\12\1\40\1\41\1\12\1\3\1\4\1\5"+
    "\1\6\1\7\1\42\1\11\3\12\1\13\1\14\1\15"+
    "\1\12\1\16\1\12\1\17\1\20\1\12\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\12\1\33\1\34\1\35\1\36\1\37\1\12\1\40"+
    "\1\41\1\12\52\0\1\43\50\0\4\12\1\44\1\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\2\12\1\45\5\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\10\12"+
    "\11\0\3\12\3\0\2\12\1\0\1\12\5\0\2\12"+
    "\1\46\3\12\1\0\10\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\5\0\2\12\1\47\3\12\1\0\10\12"+
    "\11\0\3\12\3\0\2\12\1\0\1\12\5\0\6\12"+
    "\1\0\3\12\1\50\4\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\5\0\1\12\1\51\4\12\1\0\10\12"+
    "\11\0\3\12\3\0\2\12\1\0\1\12\5\0\6\12"+
    "\1\0\6\12\1\52\1\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\5\0\4\12\1\53\1\12\1\0\10\12"+
    "\11\0\3\12\3\0\2\12\1\0\1\12\32\0\1\54"+
    "\46\0\1\55\7\0\1\56\36\0\1\57\21\0\4\12"+
    "\1\60\1\12\1\0\10\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\45\0\1\41\6\0\1\12\1\61\2\12"+
    "\1\44\1\12\1\0\10\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\3\43\1\62\1\0\42\43\5\0\1\12"+
    "\1\63\4\12\1\0\10\12\11\0\3\12\3\0\2\12"+
    "\1\0\1\12\5\0\1\64\5\12\1\0\10\12\11\0"+
    "\3\12\3\0\2\12\1\0\1\12\5\0\6\12\1\0"+
    "\10\12\11\0\1\65\2\12\3\0\2\12\1\0\1\12"+
    "\5\0\2\12\1\66\3\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\4\12"+
    "\1\67\3\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\10\12\11\0\3\12\3\0\1\70"+
    "\1\12\1\0\1\12\5\0\6\12\1\0\3\12\1\71"+
    "\4\12\11\0\3\12\3\0\2\12\1\0\1\12\5\0"+
    "\6\12\1\0\5\12\1\72\2\12\11\0\3\12\3\0"+
    "\2\12\1\0\1\12\5\0\6\12\1\0\1\12\1\73"+
    "\6\12\11\0\3\12\3\0\2\12\1\0\1\12\5\0"+
    "\2\12\1\74\3\12\1\0\10\12\11\0\3\12\3\0"+
    "\2\12\1\0\1\12\2\43\1\75\1\62\1\0\42\43"+
    "\5\0\4\12\1\76\1\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\6\12"+
    "\1\77\1\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\1\12\1\100\6\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\2\12"+
    "\1\101\5\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\2\12\1\102\5\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\2\12\1\103\3\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\4\12\1\104\3\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\5\12"+
    "\1\70\2\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\3\12\1\105\2\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\6\12\1\0\4\12"+
    "\1\106\3\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\2\12\1\107\5\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\1\12\1\110\4\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\4\12\1\111\1\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\1\12\1\112\4\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\4\12\1\113\1\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\4\12\1\114\1\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\2\12\1\115\3\12\1\0\10\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\4\12\1\116\1\12"+
    "\1\0\10\12\11\0\3\12\3\0\2\12\1\0\1\12"+
    "\5\0\6\12\1\0\3\12\1\117\4\12\11\0\3\12"+
    "\3\0\2\12\1\0\1\12\5\0\5\12\1\120\1\0"+
    "\10\12\11\0\3\12\3\0\2\12\1\0\1\12\5\0"+
    "\2\12\1\121\3\12\1\0\10\12\11\0\3\12\3\0"+
    "\2\12\1\0\1\12\5\0\4\12\1\122\1\12\1\0"+
    "\10\12\11\0\3\12\3\0\2\12\1\0\1\12";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2067];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\2\11\4\1\1\11\5\1\5\11"+
    "\1\1\3\11\2\1\1\11\5\1\1\0\10\1\4\11"+
    "\2\1\1\0\40\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	//private SimboloAbstracto nombreArchivo;
	
	public int getLinea(){
		return yyline+1;
	}
	
	public int getColumna(){
		return yycolumn+1;
	}

	/*
	public void setNombreArchivo(String nombre) {
		nombreArchivo = TablaAbstracta.texTabla.agregarSimbolo(nombre, getLinea(), getColumna());
	}

	public SimboloAbstracto getNombreArchivo() {
		return nombreArchivo;
	}
	*/


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ThinIceLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ThinIceLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { return new Symbol(SUMA, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 36: break;
        case 16: 
          { return new Symbol(AND, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 37: break;
        case 29: 
          { return new Symbol(BOOLEANO, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 38: break;
        case 27: 
          { return new Symbol(MOD, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 39: break;
        case 25: 
          { return new Symbol(DIFERENTE, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 40: break;
        case 11: 
          { return new Symbol(COR_I, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 41: break;
        case 4: 
          { return new Symbol(MULTI, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 42: break;
        case 24: 
          { return new Symbol(MENOR_IGUAL, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 43: break;
        case 10: 
          { return new Symbol(LLA_I, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 44: break;
        case 9: 
          { return new Symbol(PAR_D, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 45: break;
        case 33: 
          { return new Symbol(INT, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 46: break;
        case 19: 
          { return new Symbol(MENOR, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 47: break;
        case 18: 
          { return new Symbol(NOT, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 48: break;
        case 34: 
          { return new Symbol(BOOL, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 49: break;
        case 7: 
          { return new Symbol(PUNT_C, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 50: break;
        case 30: 
          { return new Symbol(ELSE, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 51: break;
        case 21: 
          { return new Symbol(ENTERO, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 52: break;
        case 31: 
          { return new Symbol(WHILE, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 53: break;
        case 12: 
          { return new Symbol(COR_D, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 54: break;
        case 6: 
          { return new Symbol(ID, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 55: break;
        case 20: 
          { return new Symbol(MAYOR, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 56: break;
        case 17: 
          { return new Symbol(OR, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 57: break;
        case 13: 
          { return new Symbol(IGUAL, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 58: break;
        case 1: 
          { return new Symbol(ERROR,new String("["+ getLinea() + ":" + getColumna() + "] ->\t" +  yytext() + "\tERROR"));
          }
        case 59: break;
        case 22: 
          { return new Symbol(IF, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 60: break;
        case 8: 
          { return new Symbol(PAR_I, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 61: break;
        case 5: 
          { return new Symbol(LLA_D, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 62: break;
        case 28: 
          { return new Symbol(FOR, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 63: break;
        case 35: 
          { return new Symbol(PROGRAM, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 64: break;
        case 32: 
          { return new Symbol(DO, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 65: break;
        case 26: 
          { return new Symbol(MAYOR_IGUAL, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 66: break;
        case 15: 
          { return new Symbol(RESTA, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 67: break;
        case 23: 
          { return new Symbol(ASIG, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 68: break;
        case 3: 
          { return new Symbol(DIV, new String("["+ getLinea() + ":" + getColumna() + "] -> " +  yytext()));
          }
        case 69: break;
        case 2: 
          { 
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
